CREATE DATABASE TESTE12356
GO

USE TESTE12356
GO

CREATE TABLE TB_Cliente(
	Id int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nome varchar(100) NULL
)
GO

CREATE TABLE TB_LOG(
	Id int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	LogText text NOT NULL,
	LogDate datetime NOT NULL,
) 
